name = "高可用工具集"
main = "worker.js"
compatibility_date = "2023-09-04"

# 绑定Prisma客户端
[vars]
NODE_VERSION = "18"

# 开发环境变量
[vars.development]
JWT_SECRET = "开发环境_JWT密钥"
NODE_ENV = "development"

# 生产环境变量（需要在Cloudflare Workers后台设置）
[vars.production]
NODE_ENV = "production"

# 路由配置
[[routes]]
pattern = "/api/*"
script = "worker.js"

# 静态资源（Cloudflare Pages）
[site]
bucket = "./dist"

[build]
command = "npm install"

[[d1_databases]]
binding = "DB"
database_name = "coredb"
database_id = "2ace919b-c8e2-405d-9ec0-a743903d8f41"

[observability]
enabled = true
head_sampling_rate = 1